import io
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.enums import TA_CENTER
from datetime import datetime

def generate_txt(result: dict) -> str:
    """
    Generates a plain text report from the analysis results.
    """

    report = f"""
============================================================
                     MEETMIND REPORT
============================================================

TITLE
-----
{result.get("title", "")}

SUMMARY
-------
{result.get("summary", "")}

ACTION ITEMS
------------
{result.get("action_items", "")}

KEY DECISIONS
-------------
{result.get("key_decisions", "")}

OPEN QUESTIONS
--------------
{result.get("open_questions", "")}

TRANSCRIPT
----------
{result.get("transcript", "")}

============================================================
Generated by MeetMind AI
============================================================
"""

    return report


def generate_pdf(result: dict):
    """
    Generates a PDF report and returns it as bytes.
    """

    buffer = io.BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER

    heading = styles["Heading2"]
    body = styles["BodyText"]

    story = []

    story.append(
    Paragraph(
        f"Generated on: {datetime.now().strftime('%d %B %Y, %I:%M %p')}",
        body,
    )
)

    story.append(Paragraph("MeetMind AI Report", title_style))

    story.append(Paragraph("<br/><br/>", body))

    sections = [
        ("Meeting Title", result.get("title", "")),
        ("Summary", result.get("summary", "")),
        ("Action Items", result.get("action_items", "")),
        ("Key Decisions", result.get("key_decisions", "")),
        ("Open Questions", result.get("open_questions", "")),
        ("Transcript", result.get("transcript", "")),
    ]

    for section_title, content in sections:

        story.append(Paragraph(section_title, heading))

        formatted = (
            content.replace("\n", "<br/>")
            if content
            else "No information available."
        )

        story.append(Paragraph(formatted, body))
        story.append(Paragraph("<br/>", body))

    doc.build(story)

    pdf = buffer.getvalue()
    buffer.close()

    return pdf